### ISSUE TITLE
[Bug]: DataType inconsistent for Int32 in CSV file format

### ISSUE THREAD

**Issue by lixueclaire** [alibaba/GraphAr#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Defaultly, [arrow reader for CSV](https://arrow.apache.org/docs/cpp/csv.html#data-types) does not support Int32, it will infer the data as Int64. After that, if we get vertex/edge property, which contains convert value from Int64 to Int32, it will cause an error.

### Expected Behavior

Conduct data type conversion automatically.

### Minimal Reproducible Example

```
label: person
chunk_size: 2
prefix: vertex/person/
property_groups:
  - properties:
      - name: age
        data_type: int32
        is_primary: false
    prefix: age/
    file_type: csv
version: gar/v1
```

Then, get property value of age through `VerticesCollection`.

### Environment

- Operating system: Mac OS
- GraphAr version: gar/v1
